version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Mammoth.Api/Dockerfile
    ports:
      - 80:5011
  worker:
    build:
      context: .
      dockerfile: ./Mammoth.Worker/Dockerfile
    depends_on:
      - api
  redis:
    image: "redis:5"
